server:
  port: 8080

spring:
  profiles:
    active: local

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  datasource:
    # 웹 콘솔에서 최초 한 번 접속해서 파일 생성
    # jdbc:h2:~/datajpa
    url: jdbc:h2:tcp://localhost/~/jwt
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true

## TODO: 서버 환경마다 다르게 설정해야 한다.
application:
  jwt:
    secretKey: "abcdefg12345678abcdefg12345678abcdefg12345678abcdefg12345678"
    tokenExpirationAfterMinutes: 60
    refreshTokenExpirationAfterDays: 7
    issuer: "https://www.test.com"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR